AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Music Voting App - Hottest 100 Clone

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  SpotifyClientId:
    Type: String
    Description: Spotify API Client ID
  SpotifyClientSecret:
    Type: String
    Description: Spotify API Client Secret
    NoEcho: true
  DomainName:
    Type: String
    Description: Custom domain name (e.g., vote.example.com). Leave empty to use CloudFront domain.
    Default: ''
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for custom domain (must be in us-east-1). Required if DomainName is set.
    Default: ''

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, '']]

Resources:
  # DynamoDB Tables
  BallotsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: musicvoting_ballots
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Spotify Proxy Lambda with Function URL
  SpotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: musicvoting-spotify
      CodeUri: backend_spotify/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          SPOTIFY_CLIENT_ID: !Ref SpotifyClientId
          SPOTIFY_CLIENT_SECRET: !Ref SpotifyClientSecret
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
          AllowHeaders:
            - Content-Type

  # Ballot Storage Lambda with Function URL
  BallotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: musicvoting-ballot
      CodeUri: backend_ballot/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          BALLOTS_TABLE: !Ref BallotsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BallotsTable
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - DELETE
          AllowHeaders:
            - Content-Type

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket Policy for CloudFront OAC
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontDistribution
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  # Origin Access Control for S3
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        # Custom domain configuration (includes both apex and www)
        Aliases:
          !If
            - HasCustomDomain
            - - !Ref DomainName
              - !Sub 'www.${DomainName}'
            - !Ref 'AWS::NoValue'
        ViewerCertificate:
          !If
            - HasCustomDomain
            - AcmCertificateArn: !Ref CertificateArn
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            - CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        # SPA routing - return index.html for 404s
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  SpotifyFunctionUrl:
    Description: Spotify Lambda Function URL
    Value: !GetAtt SpotifyFunctionUrl.FunctionUrl
  BallotFunctionUrl:
    Description: Ballot Lambda Function URL
    Value: !GetAtt BallotFunctionUrl.FunctionUrl
  FrontendBucketName:
    Description: S3 Bucket for Frontend
    Value: !Ref FrontendBucket
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
  CloudFrontUrl:
    Description: CloudFront URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
  CustomDomainUrl:
    Condition: HasCustomDomain
    Description: Custom Domain URL
    Value: !Sub https://${DomainName}
  WwwDomainUrl:
    Condition: HasCustomDomain
    Description: WWW Domain URL
    Value: !Sub https://www.${DomainName}
  BallotsTableName:
    Description: Ballots DynamoDB Table
    Value: !Ref BallotsTable
