AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Music Voting App - Hottest 100 Clone

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  SpotifyClientId:
    Type: String
    Description: Spotify API Client ID
  SpotifyClientSecret:
    Type: String
    Description: Spotify API Client Secret
    NoEcho: true
  DomainName:
    Type: String
    Description: Custom domain name (e.g., vote.example.com). Leave empty to use CloudFront domain.
    Default: 'warmest70.site'
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for custom domain (must be in us-east-1). Required if DomainName is set.
    Default: 'arn:aws:acm:us-east-1:079262750487:certificate/ed4b0e60-3d1d-400a-91c9-7e1a9fd47e91'

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, '']]

Resources:
  # DynamoDB Tables
  BallotsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: musicvoting_ballots
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Spotify Proxy Lambda with Function URL
  SpotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: musicvoting-spotify
      CodeUri: backend_spotify/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          SPOTIFY_CLIENT_ID: !Ref SpotifyClientId
          SPOTIFY_CLIENT_SECRET: !Ref SpotifyClientSecret
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - OPTIONS
          AllowHeaders:
            - Content-Type

  # Ballot Storage Lambda with Function URL
  BallotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: musicvoting-ballot
      CodeUri: backend_ballot/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          BALLOTS_TABLE: !Ref BallotsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BallotsTable
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - DELETE
            - OPTIONS
          AllowHeaders:
            - Content-Type

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for Music Voting Frontend

  # S3 Bucket Policy for CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        # Custom domain configuration
        Aliases:
          !If
            - HasCustomDomain
            - - !Ref DomainName
            - !Ref 'AWS::NoValue'
        ViewerCertificate:
          !If
            - HasCustomDomain
            - AcmCertificateArn: !Ref CertificateArn
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            - CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOAI}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        # SPA routing - return index.html for 404s
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  SpotifyFunctionUrl:
    Description: Spotify Lambda Function URL
    Value: !GetAtt SpotifyFunctionUrl.FunctionUrl
  BallotFunctionUrl:
    Description: Ballot Lambda Function URL
    Value: !GetAtt BallotFunctionUrl.FunctionUrl
  FrontendBucketName:
    Description: S3 Bucket for Frontend
    Value: !Ref FrontendBucket
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
  CloudFrontUrl:
    Description: CloudFront URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
  CustomDomainUrl:
    Condition: HasCustomDomain
    Description: Custom Domain URL
    Value: !Sub https://${DomainName}
  BallotsTableName:
    Description: Ballots DynamoDB Table
    Value: !Ref BallotsTable
